easy_admin:
    entities:
        HomepageSlider:
            class: App\Entity\HomepageSlider
            label: 'Homepage Slider'
            form:
                fields:
                    - { property: 'active' }
                    - { property: 'title' }
                    - { property: 'text' }
                    - { property: 'imageFile', type: 'vich_image' }
