vich_uploader:
    db_driver: orm
    mappings:
        slider_images:
            uri_prefix:         '%app.path.slider_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.slider_images%'
